### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by Nicholas-Baron** [grassator/mass#13]
I noticed that one of the goals cited in the readme is to compile with `clang` and/or `g++`. There are a few questions that this would require answers.

- [ ] 1. Build system: `Makefile`, `cmake`, or something else
I do not know if there is a way to take a `.sln` file and use it on Linux.
`cmake` has some Microsoft support, whereas `Makefile`s have none.
Given the `.bat` files already in the repository, a bash/shell script is probably the closest to the current setup.
- [ ] 2. Outputting a program
I assume that the Linux version is to output a binary runnable on Linux.
The only format with similar capabilities to PE32 (according to [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats)) is ELF.
- [ ] 3. Windows only declarations
Some declarations in the C files seem to rely on a hidden Windows dependency.
I do not know how to translate those into the Linux equivalents.

**Comment by grassator** [comment]
@Nicholas-Baron Thank you for bringing up this topic. Some of the work is to slowly progress in this direction, but there's lots more to do. I have created an [epic issue](https://github.com/grassator/mass/issues/15) to track linux-related topics that will link to other issues.

> I noticed that one of the goals cited in the readme is to compile with `clang` and/or `g++`. There are a few questions that this would require answers.
> 
> * [ ]  1. Build system: `Makefile`, `cmake`, or something else
>   I do not know if there is a way to take a `.sln` file and use it on Linux.
>   `cmake` has some Microsoft support, whereas `Makefile`s have none.
>   Given the `.bat` files already in the repository, a bash/shell script is probably the closest to the current setup.

After spending majority of my career having to deal with monstrous frontend build setups I have developed a strong allergy towards build systems. Since the project uses a single compilation, having a Makefile does not make much sense apart from convention so I'm OK either way, but I would prefer to just have `.sh` files that mimic `build.bat` and `test.bat`. Visual Studio `.sln` file is there just for debugging and is actually not setup at all, so it doesn't need an equivalent - just run the output binary with `gdb` or `lldb`. 

> * [ ]  2. Outputting a program
>   I assume that the Linux version is to output a binary runnable on Linux.
>   The only format with similar capabilities to PE32 (according to [Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats)) is ELF.

ELF support is sadly really far off. I do not want to do it the same way PE32 is done right now, which will be removed as well at some point. The goal is to have the compiler be completely unaware of what PE32, or ELF, or Mach-O and do this work inside of the meta-programming, which lacks lots of necessary features at the moment. Even then, it is likely that cross-compiling from Windows will come first.

For debugging we will also eventually need DWARF support which is a pain. To avoid per-platform debugging setups I want to experiment with user land debugging of JIT code driven from the compiler itself, but haven't had the time to try it out yet. 

> * [ ]  3. Windows only declarations
>   Some declarations in the C files seem to rely on a hidden Windows dependency.
>   I do not know how to translate those into the Linux equivalents.
Majority of things can either be replaced with LibC equivalents disabled completely on Linux, at least for now. If you want to take a stab at it and have concrete questions, I would be happy to answer them in the [newly created issue](https://github.com/grassator/mass/issues/14) that focuses specifically on making the compiler buildable on linux. It is also possible I will do a video of this basic Linux port myself in coming weeks.

One thing to note is that at present, supporting multiple platforms will slow down the development of the rest of the compiler so it is a non-priority.

I'm closing this issue in favour of more focused one referenced above.
